# Generated by Django 4.1.7 on 2023-03-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MYTEST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('na', models.CharField(max_length=10)),
                ('num', models.IntegerField()),
                ('pwd', models.TextField(max_length=12)),
            ],
        ),
    ]
