# Generated by Django 4.1.7 on 2023-03-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('email_id', models.EmailField(max_length=254)),
                ('phone_no', models.IntegerField(max_length=13)),
                ('address', models.TextField(max_length=200)),
            ],
        ),
    ]
